# Generated by Django 5.2.1 on 2026-09-17 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('year', models.PositiveBigIntegerField()),
                ('description', models.TextField()),
                ('skills', models.CharField(max_length=100)),
                ('website_link', models.URLField(max_length=2000)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='projects/pdfs/')),
            ],
        ),
    ]
