# Generated by Django 5.0.2 on 2024-04-11 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('skill1', models.CharField(max_length=250)),
                ('skill2', models.CharField(max_length=250)),
                ('skill3', models.CharField(max_length=250)),
                ('skill4', models.CharField(max_length=250)),
                ('skill5', models.CharField(max_length=250)),
                ('skill6', models.CharField(max_length=250)),
                ('skill7', models.CharField(max_length=250)),
                ('skill8', models.CharField(max_length=250)),
                ('skill9', models.CharField(max_length=250)),
                ('skill10', models.CharField(max_length=250)),
            ],
        ),
    ]
