# Generated by Django 5.0.2 on 2024-04-11 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_project1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project2',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
    ]
