# Generated by Django 5.0.2 on 2024-05-06 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_project3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post1',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title1', models.CharField(max_length=250)),
                ('title2', models.CharField(max_length=250)),
                ('description1', models.CharField(max_length=500)),
                ('description2', models.CharField(max_length=500)),
                ('description3', models.CharField(max_length=500)),
                ('description4', models.CharField(max_length=500)),
                ('description5', models.CharField(max_length=500)),
            ],
        ),
    ]
