# Generated by Django 5.2.1 on 2025-05-27 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_post1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post1',
        ),
    ]
