# Generated by Django 5.2.1 on 2025-06-12 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_delete_post1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description1',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description1', models.CharField(max_length=1000)),
                ('description2', models.CharField(max_length=1000)),
                ('description3', models.CharField(max_length=1000)),
                ('image1', models.ImageField(upload_to='images/')),
                ('image2', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
