# Generated by Django 5.2.1 on 2025-06-16 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_description1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description2',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description1', models.CharField(max_length=1000)),
                ('description2', models.CharField(max_length=1000)),
                ('description3', models.CharField(max_length=1000)),
            ],
        ),
    ]
